spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student_management?useSSL=false
    username: root
    password: 123456
jpa:
  hibernate:
     dhl-auto:none
  show-sql: true
  format-sql: true
  database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8081